####################################################################################
# Docker-compose file for spinning up a flex_conf container
# @author Benjamin Assadsolimani
#
# USAGE: docker-compose up -d
#
####################################################################################

version: '3.2'

services:
  sequelize_inquirer:
    container_name: flex_conf
    build:
      context: .
      dockerfile: Dockerfile
    image: flex_conf:latest
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      # Debug port
      - "127.0.0.1:9123:9229"
